/**
 * Popular chain brands commonly tagged on OpenStreetMap.
 * Used for autocomplete; free-text brand filters remain allowed.
 */
export const BRAND_CATALOG: string[] = [
  "Starbucks",
  "McDonald's",
  "Subway",
  "KFC",
  "Burger King",
  "Pizza Hut",
  "Domino's",
  "Dunkin'",
  "Tim Hortons",
  "Costa Coffee",
  "Pret A Manger",
  "Chipotle",
  "Taco Bell",
  "Wendy's",
  "Chick-fil-A",
  "Walmart",
  "Target",
  "Costco",
  "Aldi",
  "Lidl",
  "Tesco",
  "Sainsbury's",
  "Whole Foods",
  "Trader Joe's",
  "7-Eleven",
  "CVS",
  "Walgreens",
  "Boots",
  "Shell",
  "BP",
  "Exxon",
  "Chevron",
  "Circle K",
  "Hilton",
  "Marriott",
  "Holiday Inn",
  "Best Western",
  "Ibis",
  "Accor",
  "Bank of America",
  "Chase",
  "Wells Fargo",
  "HSBC",
  "Barclays",
  "Santander",
  "Deutsche Bank",
  "ING",
  "Apple",
  "Best Buy",
  "IKEA",
  "H&M",
  "Zara",
  "Nike",
  "Adidas",
  "Decathlon",
  "Home Depot",
  "Lowe's",
  "Ace Hardware",
  "FedEx",
  "UPS",
  "DHL",
  "Planet Fitness",
  "Anytime Fitness",
  "Equinox",
].sort((a, b) => a.localeCompare(b));
